### PR TITLE
Add Discord DM support

### PR DESCRIPTION
**Pull request by natopotato390**
Testing needed
Sooo not entirely sure if this breaks anything, everything seems to work fine to me.
This allows the bot to be controlled via direct messages instead of a server channel

"channelId" needs to be set to the direct message id
"accountOwnerRoleId" needs to be left blank. If in a server, the bot won't check for member roles. 
^^ should be added to docs

In DMs event `getMember` has no return so a different log message is needed

### CODE REVIEW

**Comment by rfresh2** [comment]
Main issues:

1. Breaks commands' role based permissions system . e.g. `.wl add steve` will throw exceptions
2. Breaks the bot nickname editing setting as nicknames are set in a guild, not on a profile
3. Accepting an empty role id in the config can lead to accidental misconfiguration. DM's working with this is more of an accidental side effect than explicitly supported

Here's the minimum bar for what I think would be needed:
1. A clearly separated and exclusive set of settings for discord bot "modes", e.g. `Guild` and `DM`. These should not share sub-settings that don't make sense. like `accountOwnerRoleId` does not make sense to be part of the DM mode's settings, be it left empty or not.
  1a. Retain the current checks when in Guild mode, i.e. the bot should crash when accountOwnerRoleId is invalid or empty.
  2a. Features like ChatRelay and changing the bot nickname should be disabled and separated from DM mode, I can't think of any good UX for how it would work in that mode.
3. Command permissions when in the DM mode has to be changed to a specific owner profile ID rather than a role ID
4. Update the `discord` command to sanely configure all the above

**Comment by natopotato390** [comment]
So I didn't realize it, a discord bot can't even send a user a DM unless they are in a server together.
The bot will have to rely on a server anyways, so guild nickname is fine.
Chat relay should just stay in a server channel, I don't think anyone wants to get a thousand DMs with 2b2t chat every day.

`the bot should crash when accountOwnerRoleId is invalid or empty.` I think changing this so that when empty, the bot ignores roles, anyone in the server can control it is a good idea. 
I get that misconfiguration is a concern, it should still crash on an invalid ID. Most discord bots i've used allowed all members to use by default unless configured otherwise.
Let me know your thoughts, don't know if it's even worth adding if refactoring permissions would be difficult.

For discord config, how about something like this:
```json
"channelId": "12345",
"channelIsDM": true,
"accountOwnerRoleId": "", // Ignores if "channelIsDM" = true. if empty, any server member can control the bot.
```

**Comment by rfresh2** [comment]
i don't think a combined guild and DM control mode is something i want to be possible. Otherwise its going to cause lots of confusion and support requests when people want to set it up.

So what you've suggested as config changes is not enough. There needs to an enum setting to specify which mode is currently being used and to switch between the modes. 

And settings like accountOwnerRoleId need to not apply or even be referenced when in the DM mode. i.e. some logic that says `if empty then DM mode` is not what I have in mind. There needs to be specific config keys for each mode.

**Comment by natopotato390** [comment]
I see. Yeah definitely a lot of work for not much.
Maybe in the future, for now I'll just use a fork, thanks for taking this into consideration.

**Pull request closed without merging**
