### PR TITLE
make discord bot support proxies

### PR DESCRIPTION
**Pull request by 4d616e61**

### CODE REVIEW

**Comment by rfresh2** [comment]
I can't get SOCKS5 to work (even without my cleanup commit), have you tested it?

```
[2023/09/07 14:33:35] [Discord] [ERROR] Failed starting discord bot
reactor.core.Exceptions$ReactiveException: javax.net.ssl.SSLException: failure when writing TLS control frames
	at reactor.core.Exceptions.propagate(Exceptions.java:408)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1710)
	at com.zenith.discord.DiscordBot.createClient(DiscordBot.java:130)
	at com.zenith.discord.DiscordBot.start(DiscordBot.java:173)
	at com.zenith.Proxy.start(Proxy.java:120)
	at com.zenith.Proxy.main(Proxy.java:84)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 5 common frames omitted
Caused by: javax.net.ssl.SSLException: failure when writing TLS control frames
	at io.netty.handler.ssl.SslHandler.setHandshakeFailureTransportFailure(SslHandler.java:1990)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Request to GET /gateway/bot [RequestStream]
	*__checkpoint ? Request to GET /gateway/bot [DefaultRouter]
```

**Comment by 4d616e61** [comment]
idk I've tested using local http proxies and it works
ill give socks proxies a shot later ig

**Comment by 4d616e61** [comment]
i think ik what the issue is
the config seems to be overridden by the default settings(which is a localhost proxy) on launch. Do you know how I can prevent this?

**Comment by 4d616e61** [comment]
nvm it doesnt work after i pull the other commit

**Comment by 4d616e61** [comment]
image

**Comment by 4d616e61** [comment]
does ur socks proxy actually work? i tested with a us datacenter one and it was ok 4 me
ill make another cleanup commit in abit

**Comment by rfresh2** [comment]
Still doesn't work and you've changed none of the critical code that would affect it. I tested my socks5 proxy with curl:

WindowsTerminal_wrqTVPLm3r

**Comment by 4d616e61** [comment]
do you mind giving mine a shot? ill dm u on discord

**Comment by rfresh2** [comment]
Note that I changed some of the JSON config schema. Example:

```
    "connectionProxy": {
      "enabled": true,
      "type": "SOCKS5",
      "host": "redacted",
      "port": 1000,
      "user": "redacted",
      "password": "redacted"
    }
```

**Comment by 4d616e61** [comment]
do u mind merging this to the 1.20 branch too? I actually intended to make a pr there but chose mainline by accident lol

**Pull request merged**
