### PR TITLE
Proxy Info Forwarding

### PR DESCRIPTION
**Pull request by hpfxd**
Implements optional support for receiving forwarded player information sent by BungeeCord or Velocity.

This allows users to connect to ZenithProxy running behind a BungeeCord/Velocity proxy and have features such as the whitelist work correctly with connecting players' UUIDs, and for logs to include the forwarded remote address.

This feature is disabled by default, and requires ZenithProxy to be running with the `verifyUsers` option disabled (due to the nature of these proxies).

The `secret` option is only for the Velocity forwarding mode and is used to verify the cryptographic signature provided with the forwarding data. This needs to match the secret configured in the Velocity proxy.

### CODE REVIEW

**Comment by rfresh2** [comment]
I'm a bit confused on what your use case is, feel free to join the discord or dm me directly on there to explain in more detail

i'm honestly kind of puzzled on why you would put zenithproxy behind bungeecord or velocity in the first place

**Comment by hpfxd** [comment]
My personal use case is because I have multiple instances of ZenithProxy, and I run them behind Velocity in order to quickly and easily switch between them.

I have a friend running this patch as well, and his use case is that he is a live streamer and is most of the time on his own server. Sometimes he plays in events on other servers not owned by him, and has ZenithProxy running behind his Velocity proxy. This allows players to easily spectate him playing in this event in-game without logging into another server.

I realize this feature may not be too useful to the average user, but I thought some may find this useful. I've tried to isolate the module from the rest of the code as much as possible to not make maintenance a burden.

**Comment by rfresh2** [comment]
Very interesting, i haven't heard of anyone using zenith like this before.

I would be more open to supporting things like this if its something users, especially anarchy players, would find useful. There's a lot of users who manage many accounts that could be interested in something to switch between them. 

Problem is, I'm still a bit unclear how you've configured your setup and what the user experience is. What do you think about providing documentation and help to others that might want to replicate it?

**Comment by hpfxd** [comment]
I do think this would be useful for users that manage multiple accounts online at the same time. Here's a demo video showing two instances of ZenithProxy online, and switching between them with Velocity.

https://github.com/rfresh2/ZenithProxy/assets/31641700/6ca13b8c-1c38-42e1-87a7-c1a1edbfc790

I can write some documentation for setting up Velocity/BungeeCord in front of ZenithProxy for users which would like to replicate this setup, and I'll be around in the Discord to help users when I can.

**Comment by rfresh2** [comment]
hmm regarding the profile switching/spoofing, i've looked into it before but there were some issues.

you can spoof the tablist packets and stuff but the main issue is when the player account is also online on the MC server (i.e. with another zenith instance). 

when the account gets in render distance, things will get weird. or if they log out during that time you're gonna get a tablist removal packet for them.

i'm not sure the best solution if there is one at all, i didn't spend a ton of time thinking about it after considering the extra complexity.

**Comment by rfresh2** [comment]
oh LOL you just made a commit regarding that but yeah

**Comment by rfresh2** [comment]
I finished up refactoring on the packet handlers in mainline. Its more like the netty pipeline now where handler codecs can be injected/removed in an ordered list

I went ahead and updated your branch but i still haven't gotten around to setting up velocity and testing if this pr still works

**Comment by rfresh2** [comment]
The account switching feature is now being added in ZenithProxy for 1.20.5 using the new transfer packet that was added

i think this covers any need to use zenith behind a velocity or bungee proxy so i'm just gonna close this

preview:
https://github.com/rfresh2/ZenithProxy/assets/89827146/21f8c8ae-849b-4181-9f1d-3f2c7f1a00fa

**Pull request closed without merging**
